___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [2]:
# CODE HERE
a = np.zeros((10))

In [3]:
# DON'T WRITE HERE

#### 3. Create an array of 10 ones

In [4]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# DON'T WRITE HERE

#### 4. Create an array of 10 fives

In [6]:
np.ones((10))*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
# DON'T WRITE HERE

#### 5. Create an array of the integers from 10 to 50

In [8]:
np.array([i for i in range(10,51)])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
# DON'T WRITE HERE

#### 6. Create an array of all the even integers from 10 to 50

In [10]:
np.array([i for i in range(10,51,2)])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
# DON'T WRITE HERE

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
arr = np.array([i for i in range(0,9)])
arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# DON'T WRITE HERE

#### 8. Create a 3x3 identity matrix

In [14]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# DON'T WRITE HERE

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [16]:
np.random.rand((1))

array([0.5832943])

In [17]:
# DON'T WRITE HERE

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [18]:
np.random.randn(25)

array([-1.49779213e+00,  1.37706232e-01, -1.16220392e+00, -1.79369829e+00,
       -8.71497273e-01, -4.92706796e-01,  6.53271750e-01, -1.71677807e+00,
       -1.12063737e+00, -6.20737753e-01,  1.50788990e-01, -6.35749279e-01,
        3.96361320e-01, -1.84366403e-01,  1.06471122e-03, -6.30813359e-01,
       -1.32590766e+00,  6.68874967e-01, -9.13301019e-01,  1.02984202e+00,
       -6.55322387e-01,  2.42169857e+00,  1.27952304e+00,  1.02307650e+00,
        1.63696982e-01])

In [19]:
# DON'T WRITE HERE

#### 11. Create the following matrix:

In [20]:
arr = np.array([i/100 for i in range(1,101)])
arr = arr.reshape((10,10))
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [21]:
# DON'T WRITE HERE

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [23]:
# DON'T WRITE HERE

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [24]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [25]:
# CODE HERE
transformMat = mat[2:,1:]
transformMat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
# DON'T WRITE HERE

#### 14. Write code that reproduces the output shown below.

In [27]:
print(mat[3,4])

20


In [28]:
# DON'T WRITE HERE

#### 15. Write code that reproduces the output shown below.

In [29]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [30]:
# DON'T WRITE HERE

#### 16. Write code that reproduces the output shown below.

In [31]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# DON'T WRITE HERE

#### 17. Write code that reproduces the output shown below.

In [33]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
# DON'T WRITE HERE

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [35]:
print(np.sum(mat))

325


In [36]:
# DON'T WRITE HERE

#### 19. Get the standard deviation of the values in mat

In [37]:
print(np.std(mat))

7.211102550927978


In [38]:
# DON'T WRITE HERE

#### 20. Get the sum of all the columns in mat

In [39]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [40]:
# DON'T WRITE HERE

## Bonus Question

We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [41]:
np.random.seed(0)
np.random.rand(100).reshape(10,10)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
        0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
        0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
        0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
        0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
        0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
        0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.9767610

# Great Job!